trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2 
  displayName: "Install .NET Core 5.0.x SDK"
  inputs:
    version: '5.0.x'
    packageType: 'sdk'

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    projects: |
      **/*.csproj
      !**/*.sqlproj
      !**/wwwroot/**/*.csproj

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    projects: |
      **/*.csproj
      !**/*.sqlproj
      !**/wwwroot/**/*.csproj

- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true