trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2 
  displayName: ".NET Core 5.0.x"
  inputs:
    version: '5.0.x'
    packageType: 'sdk'

- task: DotNetCoreCLI@2
  displayName: "Build & Restore"
  inputs:
    command: 'dotnet restore'
    projects: |
      **/*.csproj
      !**/*.sqlproj
      !**/wwwroot/**/*.csproj

- task: DotNetCoreCLI@2
  displayName: "Publish"
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 